//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPPatterns.Chap8.CoR.UI.Web.Views.Product {
    
    
    public partial class CategoryProducts {
        
        /// <summary>
        /// ProductList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ASPPatterns.Chap8.CoR.UI.Web.Views.Shared.ProductList ProductList1;
    }
}
